{% set version = '3.1-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-betareg
  version: {{ version|replace("-", "_") }}

source:
  fn: betareg_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/betareg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/betareg/betareg_{{ version }}.tar.gz
  sha256: 623f4fd4af2a4fdeb3338410dbbf2a89ef431e36ea17804ad9132f9f6fa78b1d

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-flexmix
    - r-lmtest
    - r-modeltools
    - r-sandwich
  run:
    - r-base
    - r-formula
    - r-flexmix
    - r-lmtest
    - r-modeltools
    - r-sandwich

test:
  commands:
    - $R -e "library('betareg')"           # [not win]
    - "\"%R%\" -e \"library('betareg')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=betareg
  license: GPL-2 | GPL-3
  summary: Beta regression for modeling beta-distributed dependent variables, e.g., rates and
    proportions. In addition to maximum likelihood regression (for both mean and precision
    of a beta-distributed response), bias-corrected and bias-reduced estimation as well
    as finite mixture models and recursive partitioning for beta regressions are provided.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
