{% set version = "3.2-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-betareg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/betareg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/betareg/betareg_{{ version }}.tar.gz
  sha256: f24a4e1783a9dc4ad6d46c3b3bb34eed1f4ad6cee52a3c320d8cc83d71fe41b4

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-formula                  # [build_platform != target_platform]
    - r-flexmix                  # [build_platform != target_platform]
    - r-lmtest                   # [build_platform != target_platform]
    - r-modeltools               # [build_platform != target_platform]
    - r-sandwich                 # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-formula
    - r-flexmix
    - r-lmtest
    - r-modeltools
    - r-sandwich
  run:
    - r-base
    - r-formula
    - r-flexmix
    - r-lmtest
    - r-modeltools
    - r-sandwich

test:
  commands:
    - $R -e "library('betareg')"           # [not win]
    - "\"%R%\" -e \"library('betareg')\""  # [win]

about:
  home: https://topmodels.R-Forge.R-project.org/betareg/
  license: GPL-2.0-or-later
  summary: "Beta regression for modeling beta-distributed dependent variables on the open unit interval (0, 1), e.g., rates and proportions, see Cribari-Neto and Zeileis (2010) <doi:10.18637/jss.v034.i02>. Moreover, extended-support beta regression models can accommodate dependent variables with boundary observations at
    0 and/or 1. For the classical beta regression model, alternative specifications are provided: Bias-corrected and bias-reduced estimation, finite mixture models, and recursive partitioning for beta regression, see Grün, Kosmidis, and Zeileis (2012) <doi:10.18637/jss.v048.i11>."
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - sebastian-luna-valero
